### ISSUE TITLE
Update to 4.3.1?

### ISSUE THREAD

**Issue by that0n3guy** [thomasleveil/docker-UrbanTerror#3]
Are you planning on updating to 4.3.1?

**Comment by thomasleveil** [comment]
nope, I tried and failed. I have no time/energy to figure it out. Feel free to contribute a pull request if you got it ;)

**Comment by that0n3guy** [comment]
I'll look at it, is there a reason you have 2 images for this (https://github.com/thomasleveil/docker-UrbanTerror-data)?

**Comment by thomasleveil** [comment]
when iterating over the code of https://github.com/thomasleveil/docker-UrbanTerror, I don't want to download ~1.4 GB of data to the image at each build, So https://github.com/thomasleveil/docker-UrbanTerror-data is used as the base image which already holds the data

**Comment by thomasleveil** [comment]
I'm in the process of building the `docker-UrbanTerror-data:4.3.1` image so you can work on it from there

**Comment by that0n3guy** [comment]
Thanks, that will simplify things.

**Comment by thomasleveil** [comment]
ok, so [tomdesinto/urbanterror-data:4.3.1](https://hub.docker.com/r/tomdesinto/urbanterror-data/tags/) is available -> `docker pull tomdesinto/urbanterror-data:4.3.1` to download it.

And I started branch [develop-4.3.1](https://github.com/thomasleveil/docker-UrbanTerror/tree/develop-4.3.1) in this repo, but the UrT server fails to start. I don't know why

**Comment by that0n3guy** [comment]
It would crash everytime after 

```
auth: resolving authserver address
Received signal 11, exiting...
----- Server Shutdown (Signal caught) -----
```

I disabled `auth_enable` in my server.cfg and the server would start just fine.

... so I don't have anything to push because server.cfg isn't in this docker img.

**Comment by thomasleveil** [comment]
Excellent news. I feel so dumb right now, I realize I was checking if port `27960` was opened with `netstat -lnpt`.... the `-t` option of netstat is for displaying TCP ports only while UrT is opening a UDP port 😐 

Thank you for the help 👍

**Comment by thomasleveil** [comment]
and I got it working with `auth_enable 1` with the 64bit version

**Comment by that0n3guy** [comment]
Awesome!  You must have figured out the "fps drop with the 64bit version" thing as well :).
